iname: Deploy

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "br-com-lazarodm-image-api" 
          heroku_email: "lazarodm@gmail.com"
          procfile: "web: npm start"
